site_name: Study Documentation
site_url: https://tanchuanyi.gitee.io/documentation
site_author: tanchuanyi
nav:
        - Home: index.md
        - Gitee_Usage_Guide: GiteeManageDoc/Gitee_Usage_Guide.md
        - Repo_Detail_Usage: GiteeManageDoc/Repo_Detail_Usage.md
              
        
theme: readthedocs


